### ISSUE TITLE
iBeacon Extra Byte on iBKS105

### ISSUE THREAD

**Issue by zuck-ale** [AccentSystems/iBKS-SDK-Android#1]
Hi thanks for your library,
I have a question, if I want to know the battery level of the iBeacon, how can I do?
I have enable the "iBeacon Extra Byte"

**Comment by kodartcha** [comment]
Hi zuck-ale,
When enabling iBeacon Extra Byte, one byte with the battery information will be added to the advertising packet. 

In order to retrieve it, first check if you advertising packet does include this byte. Then, get the byte 31 from the advertising result. It comes already in percentage. Do it all in the `scannedBleDevice` callback from our library.

```
@Override
public void scannedBleDevices(ScanResult result){
    String advertising = byteArrayToHex(result.getScanRecord().getBytes());
    if(advertising.substring(0,18).equalsIgnoreCase("02011a1bff4c000215") || advertising.substring(0,18).equalsIgnoreCase("0201061bff4c000215")){
        Log.i("BATTERY LEVEL", Integer.parseInt(advertising.substring(60, 62),16)+"%");
    }
}
```

The method `byteArrayToHex` converts the scan record byte array to a HEX string:

```
public static String byteArrayToHex(byte[] a) {
        StringBuilder sb = new StringBuilder(a.length * 2);
        for(byte b: a)
            sb.append(String.format("%02x", b & 0xff));
        return sb.toString();
 }
```

**Comment by zuck-ale** [comment]
Thank you very much
