### ISSUE TITLE
Required Internet Permission

### ISSUE THREAD

**Issue by dgaurav-163** [AccentSystems/iBKS-SDK-Android#2]
Hi Team

I have to know one thing, What is the requirement of Internet, Location permission in manifest. As I know I have to scan device ibks devices via blue-tooth So What is the requirement of these permissions.

Please confirm.

Thanks
Gaurav Dixit

**Comment by kodartcha** [comment]
Hi @dgaurav-163, the required permissions to scan/connect beacons in Android are:

    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

Even though the locations of the device is not used in the process of scanning and connecting with beacons, the location permissions are required just to let the user know that by scanning iBeacon devices his location may be known. As stated in the following Android documentation:

https://developer.android.com/guide/topics/connectivity/bluetooth-le.html#permissions

Hope it helps and feel free to open again the thread if there is anything not clear enough.

BR,

**Comment by dgaurav-163** [comment]
As per shared link there is no use of location permission? What is the use of Internet permission? Can you please confirm?

**Comment by kodartcha** [comment]
@dgaurav-163 please check again the shared link. Check the "**Note**" notice at the end of the **BLE Permissions** paragraph.

The internet permission in the library is required when registering an Eddystone protocol to the Google Beacon Dashboard. If this feature is not used/required, neither the internet permission is. 

iBKS SDK for Android is not required in order to use our beacons. It is just a tool in order to facilitate the developer's work. If you are capable of, or you do have a team for, you can develop your own Android application to scan and connect the the beacons using the standard tools provided by Google, and the required permissions will be only the ones stated in the above message.

BR,
